_BASE_: "../Base-SGT.yaml"
MODEL:
#  WEIGHTS: "/root/checkpoints/sgt_dla34_mot17.pth"
#  WEIGHTS: "/root/checkpoints/sgt_dla34_mot17-CH.pth"
  WEIGHTS: "/root/checkpoints/sgt_dla34_mot17half.pth"
#  WEIGHTS: "/root/checkpoints/sgt_dla34_mot17half-CH.pth"
  SGT:
    INFERENCE_GT: False
  DETECTOR:
    META_ARCHITECTURE: "CenterNet"
    WEIGHTS: "/root/checkpoints/centernet_dla34_coco.pth"
  TRACKER:
    INIT_DET_THRESH: 0.5
    GNN:
      TOPK_DET_FLAG: True
      TOPK_DET: 100
      DET_LOW_THRESH: 0.2
      NODE_MODEL:
        CLASSIFY:
          FLAG: True
          INF_THRESH: 0.4
          LOSS_WEIGHT: 10.0
      EDGE_MODEL:
        CLASSIFY:
          INF_THRESH: 0.4
#          LOSS_WEIGHT: 0.1
          LOSS_WEIGHT: 1.0
SOLVER:
  OPTIMIZER: "Adam"
  IMS_PER_BATCH: 4 # 12
  BASE_LR: 0.0002 # 0.0002
  WEIGHT_DECAY: 0.0
  STEPS: (20, )
  MAX_EPOCH: 30
#  STEPS: (50, )
#  MAX_EPOCH: 60
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 5
TEST:
  EVAL_PERIOD: 5
  EVAL_FILTER_DET_SCORE_THRESH: 0.5
  EVAL_MIN_VISIBILITY: 0.0
DATASETS:
  TRAIN: ("mix_mot17_sub_train", "mix_crowdhuman_train",)
  TEST: ("mot17_sub_val",)
#  TEST: ("mot17_test",)
INPUT:
  CLIP_BY_IMAGE: False
  FILTER_OUT_IMAGE: False
  TRAIN_MIN_VISIBILITY: 0.0
